* Install Chrome (and ssh for Windows)
You should have already followed the instructions to [[do_before.org][install software]], if you haven't, right now you should:
1. [[https://www.google.com/chrome/browser/desktop/index.html][Install Chrome]]
2. [[http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html][Install SSH (windows only)]]

* Setting Up Your Virtual Machine
** Allocating Your Virtual Machine
  1. Log on to https://vm-manage.oit.duke.edu
  2. Click "New" on the upper right.
  3. Fill out the information requested in steps 1 and 2. The input here is not critical.
  4. In step 3 - server information, choose the HTS Summer Course 
  5. Agree to the terms of use. 
  6. Click the 'Request VM' botton on the bottom left.
  7. Select *Option Configuration Network, storage, diagnostics* ->
  8. You should now be on the VM-manage panel. On the upper left, in the box labeled 'Choose a VM to manage', Click 'HTS Summer Course'.
  9. Some information regarding your virtual machine will be displayed. The crucial pieces of information are:
     - Full Name: colab-sbx-XXX.oit.duke.edu
     - Initial Password : Gobblygook
     Make a record of both of these. The XXX is some number that will be unique to each user. It identifies YOUR VM.
  
** SSH to your Virtual Machine
    1. SSH to your virtual machine
      - Mac: open a terminal, then follow the *Linux* instructions
      - Linux: At the command line, type ~ssh bitnami@colab-sbx-XXX.oit.duke.edu, then hit enter When you are prompted for the password, enter the password given to you in step 9.
      - Windows: Here are instructions for [[http://kb.mediatemple.net/questions/1595/Using+SSH+in+PuTTY+%28Windows%29][Putty]], other clients will be similar.  Hostname is colab-sbx-XXX.oit.duke.edu (the XXX is YOUR VM's id), Username is bitnami, and password is the one provided to you in step 9.
   5. If you logged in successfully, you should be presented with a "command prompt" that looks something like this:

  #+begin_src sh
bitnami@ubuntu14-generic-template-01:~$ 
  #+end_src
* Next Step
   Once you have successfully SSHed into your VM, you are ready to [[start_jupyter.org][Start Jupyter]]
